"""
Report Generation Module

Generates professional HTML and Markdown reports from analysis results.
Suitable for legal review workflows and stakeholder communication.
"""

import os
import base64
from datetime import datetime
from typing import Dict, Any

from .config import REPORT_COLORS, SEVERITY_LABELS


class ReportGenerator:
    """Generate formatted reports from contract analysis results."""

    def __init__(self):
        self.colors = REPORT_COLORS

    def generate_html(self, result: Dict[str, Any], output_path: str = "report.html") -> str:
        """Generate professional HTML report."""
        risk = result.get("risk_summary", {})
        compliance = result.get("compliance", {})
        clauses = result.get("clauses", [])

        html = self._build_html_report(result, risk, compliance, clauses)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        return output_path

    def generate_markdown(self, result: Dict[str, Any]) -> str:
        """Generate Markdown report."""
        risk = result.get("risk_summary", {})
        compliance = result.get("compliance", {})
        clauses = result.get("clauses", [])

        lines = [
            "# Legal Contract Analysis Report",
            "",
            f"**Document:** {result.get('filename', 'Unknown')}",
            f"**Analysis Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"**Analyzed By:** Legal Contract Analyzer v1.0.0",
            f"**Analyst:** Nwaeke Calixtus Ifeanyi, Esq. (AI & Legal)",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
        ]

        # Risk summary
        score = risk.get("overall_score", 0)
        level = risk.get("risk_level", "unknown")
        lines.extend([
            f"### Risk Assessment: {level.upper()} (Score: {score}/5.0)",
            "",
            f"- **Total Clauses Found:** {risk.get('total_clauses', 0)}",
            f"- **High Risk Clauses:** {risk.get('high_risk_clauses', 0)}",
            f"- **Critical Risk Clauses:** {risk.get('critical_risk_clauses', 0)}",
            "",
        ])

        # Recommendations
        if risk.get("recommendations"):
            lines.extend(["### Key Recommendations", ""])
            for rec in risk["recommendations"][:5]:
                lines.append(f"- {rec}")
            lines.append("")

        # Compliance
        comp_score = compliance.get("compliance_score", 0)
        comp_level = compliance.get("compliance_level", "unknown")
        lines.extend([
            "## Compliance Check",
            "",
            f"**Score:** {comp_score}% ({comp_level})",
            "",
            f"- **Required Clauses:** {compliance.get('required_clauses', {}).get('present', 0)}/"
            f"{compliance.get('required_clauses', {}).get('total', 0)} present",
            f"- **Recommended Clauses:** {compliance.get('recommended_clauses', {}).get('present', 0)}/"
            f"{compliance.get('recommended_clauses', {}).get('total', 0)} present",
            "",
        ])

        if compliance.get("missing_clauses"):
            lines.extend(["### Missing Clauses", ""])
            for missing in compliance["missing_clauses"][:10]:
                lines.append(
                    f"- **{missing['clause_name']}** ({missing['importance']}): "
                    f"{missing['risk_of_absence']}"
                )
            lines.append("")

        # Clause details
        if clauses:
            lines.extend([
                "## Extracted Clauses",
                "",
            ])
            for clause in clauses[:15]:
                lines.extend([
                    f"### {clause.get('type_name', 'Unknown')}",
                    "",
                    f"**Confidence:** {clause.get('confidence', 0) * 100:.1f}%",
                    "",
                    f"> {clause.get('extracted_text', '')[:400]}...",
                    "",
                ])
                if clause.get("risk_factors"):
                    lines.append("**Risk Factors:**")
                    for rf in clause["risk_factors"]:
                        lines.append(f"- {rf.get('description', '')}")
                    lines.append("")

        lines.extend([
            "---",
            "",
            "*Generated by Legal Contract Analyzer*",
            "*This report is for informational purposes and does not constitute legal advice.*",
        ])

        return "\n".join(lines)

    def _build_html_report(
        self,
        result: Dict[str, Any],
        risk: Dict[str, Any],
        compliance: Dict[str, Any],
        clauses: list,
    ) -> str:
        """Build full HTML report document."""
        score = risk.get("overall_score", 0)
        level = risk.get("risk_level", "low")
        color = self.colors.get(level, self.colors["info"])

        clause_rows = ""
        for clause in clauses[:20]:
            c_color = self.colors.get("info")
            c_risks = "<br>".join(
                f"&bull; {r.get('description', '')}"
                for r in clause.get("risk_factors", [])
            ) or "No specific risk factors detected"

            clause_rows += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #ddd;">
                    <strong>{clause.get('type_name', 'Unknown')}</strong><br>
                    <span style="color:#888;font-size:12px;">ID: {clause.get('id', '')}</span>
                </td>
                <td style="padding:10px;border-bottom:1px solid #ddd;">{clause.get('confidence', 0)*100:.0f}%</td>
                <td style="padding:10px;border-bottom:1px solid #ddd;font-size:13px;">
                    {clause.get('extracted_text', '')[:250]}...
                </td>
                <td style="padding:10px;border-bottom:1px solid #ddd;font-size:12px;">{c_risks}</td>
            </tr>
            """

        recommendations_html = ""
        for rec in risk.get("recommendations", []):
            recommendations_html += f"<li style='margin:8px 0;'>{rec}</li>"

        missing_html = ""
        for m in compliance.get("missing_clauses", [])[:10]:
            badge_color = "#F44336" if m["importance"] == "REQUIRED" else "#FF9800"
            missing_html += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #ddd;">
                    <strong>{m['clause_name']}</strong>
                </td>
                <td style="padding:10px;border-bottom:1px solid #ddd;">
                    <span style="background:{badge_color};color:white;padding:3px 8px;border-radius:3px;font-size:12px;">
                        {m['importance']}
                    </span>
                </td>
                <td style="padding:10px;border-bottom:1px solid #ddd;font-size:13px;">{m['risk_of_absence']}</td>
                <td style="padding:10px;border-bottom:1px solid #ddd;font-size:13px;">{m['recommendation']}</td>
            </tr>
            """

        risk_dist = risk.get("risk_distribution", {})
        dist_html = ""
        for lvl in ["low", "medium", "high", "critical"]:
            count = risk_dist.get(lvl, 0)
            c = self.colors.get(lvl, "#999")
            dist_html += f"""
            <div style="display:inline-block;margin:10px;text-align:center;">
                <div style="font-size:24px;font-weight:bold;color:{c};">{count}</div>
                <div style="font-size:12px;text-transform:uppercase;color:#888;">{lvl}</div>
            </div>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Contract Analysis Report - {result.get('filename', 'Document')}</title>
<style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; margin:0; padding:0; background:#f5f5f5; color:#333; }}
.container {{ max-width:1000px; margin:20px auto; padding:20px; background:white; box-shadow:0 2px 10px rgba(0,0,0,0.1); }}
h1 {{ color:#1a365d; border-bottom:3px solid #1a365d; padding-bottom:10px; }}
h2 {{ color:#1a365d; margin-top:30px; border-bottom:1px solid #ddd; padding-bottom:8px; }}
h3 {{ color:#555; }}
table {{ width:100%; border-collapse:collapse; margin:15px 0; font-size:13px; }}
th {{ background:#1a365d; color:white; padding:12px 10px; text-align:left; }}
td {{ padding:10px; border-bottom:1px solid #eee; }}
.risk-badge {{ display:inline-block; padding:8px 16px; border-radius:20px; color:white; font-weight:bold; font-size:18px; }}
.metric {{ background:#f8f9fa; padding:15px; border-left:4px solid #1a365d; margin:10px 0; }}
.footer {{ margin-top:40px; padding-top:20px; border-top:2px solid #ddd; font-size:12px; color:#888; text-align:center; }}
.disclaimer {{ background:#fff8e1; border-left:4px solid #ffb74d; padding:12px; margin:15px 0; font-size:13px; }}
</style>
</head>
<body>
<div class="container">
<h1>Legal Contract Analysis Report</h1>

<div style="display:flex;justify-content:space-between;flex-wrap:wrap;margin:20px 0;">
    <div><strong>Document:</strong> {result.get('filename', 'Unknown')}</div>
    <div><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
    <div><strong>Analyst:</strong> Nwaeke Calixtus Ifeanyi, Esq.</div>
</div>

<div class="disclaimer">
<strong>Legal Disclaimer:</strong> This report is generated by an AI-powered analysis tool
and is for informational purposes only. It does not constitute legal advice.
Always consult a qualified attorney before making legal decisions.
</div>

<!-- RISK SUMMARY -->
<h2>Risk Assessment</h2>
<div style="text-align:center;margin:20px 0;">
    <span class="risk-badge" style="background:{color};">
        {level.upper()} RISK &mdash; {score}/5.0
    </span>
</div>

<div style="text-align:center;margin:20px 0;">
    {dist_html}
</div>

<div class="metric">
    <strong>Total Clauses Found:</strong> {risk.get('total_clauses', 0)}<br>
    <strong>High Risk Clauses:</strong> {risk.get('high_risk_clauses', 0)}<br>
    <strong>Critical Risk Clauses:</strong> {risk.get('critical_risk_clauses', 0)}
</div>

<!-- RECOMMENDATIONS -->
<h3>Key Recommendations</h3>
<ul>{recommendations_html}</ul>

<!-- COMPLIANCE -->
<h2>Compliance Check</h2>
<div class="metric">
    <strong>Compliance Score:</strong> {compliance.get('compliance_score', 0)}%<br>
    <strong>Status:</strong> {compliance.get('compliance_level', 'Unknown')}<br>
    <strong>Required:</strong> {compliance.get('required_clauses', {}).get('present', 0)}/
    {compliance.get('required_clauses', {}).get('total', 0)} present |
    <strong>Recommended:</strong> {compliance.get('recommended_clauses', {}).get('present', 0)}/
    {compliance.get('recommended_clauses', {}).get('total', 0)} present
</div>

<h3>Missing Clauses</h3>
<table>
<thead><tr><th>Clause</th><th>Importance</th><th>Risk of Absence</th><th>Recommendation</th></tr></thead>
<tbody>{missing_html}</tbody>
</table>

<!-- EXTRACTED CLAUSES -->
<h2>Extracted Clauses ({len(clauses)} found)</h2>
<table>
<thead><tr><th>Clause Type</th><th>Confidence</th><th>Extracted Text</th><th>Risk Factors</th></tr></thead>
<tbody>{clause_rows}</tbody>
</table>

<div class="footer">
<p>Generated by Legal Contract Analyzer v1.0.0</p>
<p>Built by Nwaeke Calixtus Ifeanyi, Esq. &mdash; Legal Practitioner | AI & Data Scientist</p>
<p><em>This report does not constitute legal advice. Consult a qualified attorney.</em></p>
</div>
</div>
</body>
</html>"""
